### PR TITLE
[FIX] Fix CI and some tests

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

Changes proposed in this pull request:

- Fix link I added to badge in #37.
- Ignore subfolder of tests.
- Drop caching of py27 and py36 environments. There's almost definitely a way to cache all of them, but after some testing in NiMARE I kept having one environment's step overwriting the others.
- Pin statsmodels version by Python version.
- Fix a couple of tests.

### CODE REVIEW

**Comment by bbfrederick** [comment]
Is there a way to limit the testing to ${RAPIDTIDEHOME}/rapidtide/tests?  I moved a bunch of failing tests into ${RAPIDTIDEHOME}/rapidtide/candidatetests hoping they'd be ignored, but circleCI went ahead and ran them anyway (and failed).

**Comment by tsalo** [comment]
In the config file, where there is `py.test rapidtide` you can put `py.test --ignore=rapidtide/candidatetests rapidtide`. That will ignore the `candidatetests` folder.

**Comment by tsalo** [comment]
There's still a bug in `test_spectrogram.py` that I'm not sure how to fix, but other than that, things seem to be running properly.

**Comment by tsalo** [comment]
The only thing still failing is the style check, which is fine, although I'm not sure why all of the individual jobs aren't showing up as status checks.

**Pull request merged**
