### PR TITLE
Add codespell support (config, workflow to detect/not fix) and make it fix few typos

### PR DESCRIPTION
**Pull request by yarikoptic**
Missed your talk yesterday :-/ mind sharing slides for a peak?

More about codespell: https://github.com/codespell-project/codespell .

I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.

CI workflow has 'permissions' set only to 'read' so also should be safe.

### CODE REVIEW

**Comment by bbfrederick** [comment]
It's been 3 months since the last non-dependabot PR, and you and I both put one in within a 1 or 2 minute period.  What are the odds?

I'll need to make sure they don't clash - mine's a pretty big one, and has a number of documentation patches.

I don't think you really missed much in my talk - we ran over time so didn't get to mention a lot of what we wanted to talk about.  Happy to send you the slides though.

**Comment by yarikoptic** [comment]
> What are the odds?

Last minute ~~shopping~~work before the holidays?!

You could have easily delayed my PR -- the last commit(s) are rerunnable, so we could pretty much `datalad rerun --onto fresh-master` the whole thing on top of your new state of things after you are done!

**Comment by bbfrederick** [comment]
Turns out they didn't clash at all (my PR had some things that had to be manually merged, but that's because I moved around and renamed a lot of file and git was NOT happy about it).  They're both in now.  I forgot to put your name into pyproject.toml, but it's in there now for 3.0alpha2.

**Comment by yarikoptic** [comment]
Oi... am I responsible for it now? ;-)

**Pull request merged**
