### PR TITLE
[FIX, DOC] Fix badge in README and docs

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

Changes proposed in this pull request:

- Fix the badge path in the README (I messed it up in #38).
- Switch the badge in the docs' index.rst from TravisCI to CircleCI.

### CODE REVIEW

**Comment by tsalo** [comment]
Would you mind enabling the [circleci-artifacts-redirector](https://github.com/apps/circleci-artifacts-redirector/) and [CircleCI Checks](https://circleci.com/docs/2.0/enable-checks/) GitHub apps on this repo? They should help with the status checks.

`circleci-artifacts-redirector` will add a new status check pointing to the documentation build's artifacts, so you can browse the documentation site before merging.

`CircleCI Checks` _should_ split the overall CircleCI workflow into separate job-specific status checks, which should let you set up branch protection rules so that you don't merge PRs that fail tests, for example, without restricting based on the style check. You can always force those PRs through if you want, but the extra check should help.

**Comment by bbfrederick** [comment]
As far as I can tell, they are enabled (I know circleci-artifacts-redirector is).  The other one looks like it's enabled, but following the directions seems to just keep taking me back to a GitHub page saying I need to enable it on CircleCI...

**Comment by tsalo** [comment]
I'm sorry getting these things set up is such a slog. I've done it a few times, but every time it's like I have to relearn it.

When you go to this repository's Settings --> Integrations --> circleci-artifacts-redirector, and hit the Configure button, it should take you to the "Installed GitHub Apps" tab in your account settings. 

When you scroll down to the "Repository access" section, does it have `rapidtide` selected, either via "All repositories" or listed specifically under "Only select repositories"?

**Comment by bbfrederick** [comment]
No need to apologize!  I really appreciate the effort getting this running, as I clearly don't know how to do it...

In answer to your question, yes.  According to the Installed GitHub App circleci-artifacts-redirector page, it has access to all repositories.

**Comment by tsalo** [comment]
>In answer to your question, yes. According to the Installed GitHub App circleci-artifacts-redirector page, it has access to all repositories.

Okay... I'll try closing this PR and reopening it. Maybe that will trigger it?

> It does look like all the tests are running - it's just that it's failing the style check, and it's upset about that. You mentioned that I could make is so the style check didn't count as a "real" test, right?

Once the individual jobs in the CircleCI workflow show up as separate status checks here (which `CircleCI Checks` _should_ do), you can designate some as "required". Required status checks block PRs from being merged if they fail, although you, as the owner of the repo, can choose to ignore the blocking status checks and merge anyway. The benefit is that you can easily see why things are failing without having to open any separate pages.

Check out this PR I have open for tedana: https://github.com/ME-ICA/tedana/pull/591.
We have one required status check, `merge_coverage`, which builds off of most of the other jobs within the CircleCI workflow. You'll also notice that all of those individual jobs show up as status checks. That's the thing that should be happening here.

There's also a status check that renders the documentation. The exact method is slightly different in tedana (i.e., it uses a GitHub webhook directly from ReadTheDocs, while here we are using `circleci-artifacts-redirector`). The idea there is that you can just follow that status check's link and view the documentation as it would render on the site after merging the PR.

**Pull request closed without merging**
