### PR TITLE
[FIX, DOC] Fix badge in README and docs

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

Changes proposed in this pull request:

- Fix the badge path in the README (I messed it up in #38).
- Switch the badge in the docs' index.rst from TravisCI to CircleCI.

### CODE REVIEW

**Comment by tsalo** [comment]
Continuing from #39... well, that didn't work.

I did some testing with another repository. It turns out enabling CircleCI Checks was a mistake. It seems to move all of the individual jobs into the Checks tab, while only keeping the overall workflow in the status checks on the main tab for the PR. Could you disable it?

**Comment by tsalo** [comment]
Once that's disabled and I can push another commit to trigger CI, it should have status checks a lot like the ones in this PR: https://github.com/neurostuff/NiMARE/pull/295.

**Comment by bbfrederick** [comment]
I've disabled it.  Hope that helps!

**Comment by tsalo** [comment]
It worked!!!! You can merge this if you want.

I'd recommend making `test_py27`, `test_py36`, and `test_py37_with_coverage` required.

**Pull request merged**
