### PR TITLE
Update fMRIPrep-related documentation

### PR DESCRIPTION
**Pull request by tsalo**
Closes none. I'm trying to translate the settings we're planning to use in fMRIPost-rapidtide into recommendations in rapidtide's documentation.

Changes proposed in this pull request:

- fMRIPrep outputs all of the transforms you might need, so I removed a comment about extracting transforms from the working directory.
- Change recommended interpolation method for aparc+aseg files from NearestNeighbor to GenericLabel.
- I added a tip to use the gray matter mask derived from fMRIPrep for `--globalmeaninclude` (already recommended), `--refineinclude`, and `--offsetinclude`.
    - @bbfrederick I want to make sure this is a good tip- it's what I have in fMRIPost-rapidtide, so if I'm wrong to recommend it I should modify fMRIPost-rapidtide as well.
- Some formatting changes to the associated sections. I broke a few lines on punctuation and code-formatted arguments in the text.

### CODE REVIEW

**Comment by bbfrederick** [comment]
All good suggestions and changes.  The wording about extracting transforms from the working directory is from the bad old days before these were output by default.

I'm leaning towards using the gray matter mask for globalmeaninclude as well.  In fact, along those lines, there is a new capability in the last few versions that I haven't documented yet - instead of supplying the masks individually, you can just give rapitdide ``--brainmask``,  ``--graymattermask`` and ``--whitemattermask``, and it sets the internal masks based on whatever current theory I have about what regions are good to use for each one (if you explicitly set any of the masks on the command line it overrides the "standard" behavior for that mask.

**Comment by bbfrederick** [comment]
I'm not sure what's making build_docs fail - sphinx is a bit of a black box to me; the documentation broke a while back and I threw code at the wall until it started working again then ran way - I'm afraid to touch it now :-).

**Comment by tsalo** [comment]
I have been using those three parameters when processing 28andMe. I'm happy to modify the fMRIPrep recommendations to use those parameters instead. If you use `--graymattermask`, should you still use the same mask for `--refineinclude` as well? For healthy young adults, I mean.

Also... since these mask files are binarized automatically with a threshold of 0.1, do you still recommend binarizing fMRIPrep probseg files before using them?

The two problems I stumbled across are that the intersphinx mapping dictionary was formatted in a way that isn't supported anymore and m2r recently started breaking. m2r has been unmaintained for a while, so I believe the current recommendation is to use myst_parser, which is what I'm trying.

**Comment by tsalo** [comment]
I definitely don't have strong feelings about it. For the fMRIPrep recommendations, I can just not make one regarding refineinclude.

**Comment by tsalo** [comment]
Okay, I think the recommendations are fairly solid/up-to-date now. What do you think?

**Comment by bbfrederick** [comment]
Looks good.  I'll merge it.

**Comment by bbfrederick** [comment]
Actually, NOW I'll merge it.

**Comment by tsalo** [comment]
Thanks! Although it looks like you closed without merging.

**Comment by bbfrederick** [comment]
That explains a lot.  But why is build_docs failing again?

**Comment by tsalo** [comment]
I think that's just a dumb mistake on my part. I just pushed a fix, but you should wait to make sure it works before merging.

**Comment by tsalo** [comment]
Argh, the changelog page is being rendered (i.e., the URL exists), but it's not showing up in the sidebar.

**Comment by bbfrederick** [comment]
build_docs passed, and I have no reason to think the coverage test will fail (since no code changed).  Merge?

**Comment by tsalo** [comment]
I just need to fix the changelog. I think I know what's wrong though.

**Comment by bbfrederick** [comment]
Ok.  Are we .md free going forward?

**Comment by tsalo** [comment]
Not quite. It's actually basically the same as before, where whatsnew.rst just collects the contents of CHANGELOG.md, but using `myst_parser` instead of `m2r` or `recommonmark`, since both of the latter are unmaintained at this point.

**Comment by tsalo** [comment]
The sidebar looks good now! 
image

**Pull request merged**
