### PR TITLE
[TST, DOC] Switch CI to CircleCI

### LINKED ISSUE #34: Build docs in CI
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would help when opening pull requests to be able to check over the documentation as it renders on RTD.

**Describe the solution you'd like**
I don't know if it's supported in Travis, but CircleCI makes it pretty easy to build docs as a workflow within the continuous integration. See [here](https://github.com/neurostuff/NiMARE/blob/e602f78fe3d52d5fb2cc558abfc0e16b0e1f0b37/.circleci/config.yml#L39-L55) for an example.

That example could also cover the Python version-specific tests with minimal changes.

**Describe alternatives you've considered**
There's an RTD integration that may work, but I couldn't get it to work on one of my projects, so I lean toward CircleCI's method.

**Additional context**
I'd be happy to open a PR for this.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #34 and #35.

Changes proposed in this pull request:

- Add CircleCI config files. This includes the following workflows:
    - Python 2.7 tests
    - Python 3.6 tests
    - Python 3.7 environment build
    - Python 3.7 tests + coverage
    - Linting
    - Build docs and store artifacts
    - Deploy to PyPi (only on tags matching `/[0-9]+(\.[0-9]+)*/`)
- Remove Travis config file.
- Turn RTD config file back on. I'm happy to debug if the RTD build fails.

### CODE REVIEW

**Comment by tsalo** [comment]
@bbfrederick can you enable CircleCI for this repo? You should be able to sign up for an account at https://app.circleci.com with your GitHub credentials. Then you can give CircleCI permissions for rapidtide specifically.

**Comment by tsalo** [comment]
Under project settings, I'd recommend the following:

Advanced Settings:
- Build forked pull requests: On
- Only build pull requests: On
- Auto-cancel redundant builds: On

Environment Variables:
- PYPI_PASSWORD: Password for your pypi.org account.
- PYPI_USER: Username for your pypi.org account.

**Comment by tsalo** [comment]
Could you ping me when you have the project enabled on CircleCI? That way I can open a new PR with updates to the badges to test it.

**Comment by bbfrederick** [comment]
As far as I can tell, it is now enabled and set up as you suggested.  The first build failed, but that's not a big surprise.

**Comment by tsalo** [comment]
Awesome! I think I messed up the link when I checked it myself, but I see it now. I'll open a PR to test it out.

**Comment by tsalo** [comment]
I see the problem. You need to enable third-party orbs. You can do that under "Organization Settings" --> "Security" --> "Allow Uncertified Orbs": Yes

**Comment by bbfrederick** [comment]
Done

**Pull request merged**
